### ISSUE TITLE
Expand docs to include details on adding custom font

### ISSUE THREAD

**Issue by adeleke5140** [joaopaulomoraes/reactjs-vite-tailwindcss-boilerplate#114]
**Is your feature request related to a problem? Please describe.**
Thank you for creating this boilerplate. I recently had to add a custom local font to my app and it was difficult to figure out.

**Describe the solution you'd like**
It would be great if the docs had a section that informed users on how to do that. This would ensure that folks who use your boilerplate aren't confused in that respect. 

I solved this by creating an `index.css` file and initialising `tailwind` in it. This provided me with the ability to use custom local fonts saved in my `/public` directory.

**Describe alternatives you've considered**
Null

**Additional context**
Null

**Comment by joaopaulomoraes** [comment]
Heym @adeleke5140!

I'm glad you liked boilerplate and are using it in your projects ❤️ .

I believe your approach to custom or external fonts like Google Fonts is correct.

As it is a specific use case that can be solved easily, I believe that it is not necessary to create a doc for this, as the idea of ​​the boilerplate is to solve the most complex and boring tooling problems and then start modeling and build your application.

I will close the issue for this reason, but I will remain at your disposal if you have questions about this or other implementations.
