### ISSUE TITLE
missing automatic sort in tailwind

### ISSUE THREAD

**Issue by Renan-Olovics** [joaopaulomoraes/reactjs-vite-tailwindcss-boilerplate#125]
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

**Comment by joaopaulomoraes** [comment]
Eslint already does this with `tailwindcss/classnames-order`.

https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/classnames-order.md

https://github.com/joaopaulomoraes/reactjs-vite-tailwindcss-boilerplate/assets/16243531/e38b958c-e374-415d-b7e2-5f08eebb64be

_You may need to install the extension in your IDE_
