### ISSUE TITLE
Sabe como fazer o roteamento? Estou sofrendo pois pela vercel está aparecendo 404

### ISSUE THREAD

**Issue by lei0gre** [joaopaulomoraes/reactjs-vite-tailwindcss-boilerplate#129]
Simplesmente, não parece que vercel está entendendo o vite e não consigo rotear apenas com react-router-dom, precisa de alguma configuração que desconheço...

`<Router>
  <Routes>
  <Route path="/" element={<AppContent />} />
  <Route path="/booster" element={<BecomeBooster />} />
  </Routes>
  </Router>`

**Comment by joaopaulomoraes** [comment]
Acredito que você precisa ter um [`vercel.json`](https://vercel.com/docs/projects/project-configuration#redirects-examples) configurado e adicionar uma pequena regra para sempre apontar para o seu `index.html`.

```js
{
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
  ]
}
```

**Comment by lei0gre** [comment]
Nâo funcionou :/ ...

**Comment by joaopaulomoraes** [comment]
Se puder dar mais contexto fica mais fácil te ajudar. Fique a vontade para entrar em contato ou me mandar uma dm no Twitter ou similar.

De qualquer forma, esse não é um problema com o boilerplate, nesse caso, estarei fechando essa issue.

**Comment by lei0gre** [comment]
Na verdade funcionou joão, ele tinah travado na vercel por conta  package-lock.json, agora foi. valeu amigo!!!
