### ISSUE TITLE
first run - 'react is not defined'

### ISSUE THREAD

**Issue by shedali** [joaopaulomoraes/reactjs-vite-tailwindcss-boilerplate#3]
- following readme instructions
- npm install, npm run dev

![image](https://user-images.githubusercontent.com/64362/141682220-38e4a779-96fc-45f2-affc-43f4b06f1a5c.png)

```
 node --version
v16.13.0
npm --version
8.1.0
```

**Comment by joaopaulomoraes** [comment]
Thanks for report, @shedali! I provide a fix just now with some improvements in #4.
