### ISSUE TITLE
False linter error on vscode

### ISSUE THREAD

**Issue by eleloi** [joaopaulomoraes/reactjs-vite-tailwindcss-boilerplate#33]
Hi!

I don't think this is a Bug, but a local problem. My vscode linter claims that, for example 

`import Avatar from 'components/Avatar'`
Cannot find module 'components/Avatar' or its corresponding type declarations

But the dev server works well.

It's that an tsconfig.json issue?

**Comment by joaopaulomoraes** [comment]
Him @eleloi, thanks for the report!

Could you provide more information about the environment please? I did the README step by step from scratch and I couldn't reproduce the problem.

Tip: Please, check that the installed `node` version is not too old or that you are not using an outdated (global) version of typescript 👍🏼

**Comment by eleloi** [comment]
That's it! I update typescript global node package and the issue goes away!

Thank you for your work @joaopaulomoraes
