### ISSUE TITLE
Missing types for jest-dom

### ISSUE THREAD

**Issue by harmyderoman** [joaopaulomoraes/reactjs-vite-tailwindcss-boilerplate#51]
TS throw errors. I solved it by adding @types/testing-library__jest-dom.
I use @testing-library/jest-dom version 5.16.4

**Comment by joaopaulomoraes** [comment]
Could you please provide a testable example, @harmyderoman?

**Comment by joaopaulomoraes** [comment]
Which package manager are you using?

**Comment by harmyderoman** [comment]
> Which package manager are you using?

pnpm

**Comment by joaopaulomoraes** [comment]
I've done the README process from scratch, using other management packs, and unfortunately I haven't been able to reproduce the problem.

If you have more details that can help with the debug that would be great, if not we can close this issue for now and reopen if something new changes/happens.

Thanks for helping :p

**Comment by harmyderoman** [comment]
The error I've got in the file `test.tsx`:
```
Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'.ts(2339)
```

**Comment by joaopaulomoraes** [comment]
Do you follow the README steps? I reproduce the necessary steps and I couldn't catch this error

**Comment by joaopaulomoraes** [comment]
I will be closing this issue, if I have more details or steps to reproduce the problem, it can be reopened, thanks ❤️
